logging:
  level:
    ROOT: INFO
    com.dogukanhan.kodgemisi.simplehr: INFO
spring:
  profiles:
    active: prod
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost/test
    username:
    password:
  h2:
    console:
      enabled: true
  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
    database-platform: org.hibernate.dialect.H2Dialect